CREATE TABLE burgers (
id int AUTO_INCREMENT,
burger_name varchar(30) NOT NULL,
devoured BOOLEAN DEFAULT false,
PRIMARY KEY (id),
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
